FROM python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir mlflow[sqlalchemy]==2.14.1
# Crear directorio para backend/artifacts
RUN mkdir -p /mlflow/artifacts
ENV MLFLOW_BACKEND=sqlite:////mlflow/mlflow.db
ENV MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
EXPOSE 5000
CMD mlflow server     --host 0.0.0.0 --port 5000     --backend-store-uri ${MLFLOW_BACKEND}     --default-artifact-root ${MLFLOW_ARTIFACT_ROOT}
