FROM python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir fastapi==0.111.0 uvicorn==0.30.1 mlflow==2.14.1 pandas==2.2.2
COPY src/service.py src/service.py
EXPOSE 8080
CMD ["uvicorn", "src/service:app", "--host", "0.0.0.0", "--port", "8080"]
